using System;
using System.Drawing;
using System.Windows.Forms;

namespace ASE_Assignment
{

    /*
     * Window.Designer: This class is auto generated by VS and generates the application form and all its assets.
     */
    public partial class Window
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {   
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.menuFile = new System.Windows.Forms.ToolStripMenuItem();
            this.menuLoad = new System.Windows.Forms.ToolStripMenuItem();
            this.menuSave = new System.Windows.Forms.ToolStripMenuItem();
            this.menuQuit = new System.Windows.Forms.ToolStripMenuItem();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.turtle = new System.Windows.Forms.PictureBox();
            this.clearScreen = new System.Windows.Forms.Button();
            this.clearMethod = new System.Windows.Forms.Button();
            this.clearVars = new System.Windows.Forms.Button();
            this.clearButton = new System.Windows.Forms.Button();
            this.executeButton = new System.Windows.Forms.Button();
            this.invalidBox = new System.Windows.Forms.Label();
            this.commandBox = new System.Windows.Forms.Label();
            this.enterButton = new System.Windows.Forms.Button();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.saveFileDialog1 = new System.Windows.Forms.SaveFileDialog();
            this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            this.consoleBox = new System.Windows.Forms.TextBox();
            this.menuStrip1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.turtle)).BeginInit();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.menuFile});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(1217, 24);
            this.menuStrip1.TabIndex = 1;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // menuFile
            // 
            this.menuFile.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.menuLoad,
            this.menuSave,
            this.menuQuit});
            this.menuFile.Name = "menuFile";
            this.menuFile.Size = new System.Drawing.Size(37, 20);
            this.menuFile.Text = "File";
            // 
            // menuLoad
            // 
            this.menuLoad.Name = "menuLoad";
            this.menuLoad.Size = new System.Drawing.Size(100, 22);
            this.menuLoad.Text = "Load";
            this.menuLoad.Click += new System.EventHandler(this.LoadButton_Clicked);
            // 
            // menuSave
            // 
            this.menuSave.Name = "menuSave";
            this.menuSave.Size = new System.Drawing.Size(100, 22);
            this.menuSave.Text = "Save";
            this.menuSave.Click += new System.EventHandler(this.SaveButton_Clicked);
            // 
            // menuQuit
            // 
            this.menuQuit.Name = "menuQuit";
            this.menuQuit.Size = new System.Drawing.Size(100, 22);
            this.menuQuit.Text = "Quit";
            this.menuQuit.Click += new System.EventHandler(this.quitButton_Clicked);
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Left;
            this.splitContainer1.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.splitContainer1.IsSplitterFixed = true;
            this.splitContainer1.Location = new System.Drawing.Point(0, 24);
            this.splitContainer1.Name = "splitContainer1";
            this.splitContainer1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.BackColor = System.Drawing.Color.White;
            this.splitContainer1.Panel1.Controls.Add(this.turtle);
            this.splitContainer1.Panel1.Paint += new System.Windows.Forms.PaintEventHandler(this.splitContainer1_Panel1_Paint);
            this.splitContainer1.Panel1MinSize = 50;
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.clearScreen);
            this.splitContainer1.Panel2.Controls.Add(this.clearMethod);
            this.splitContainer1.Panel2.Controls.Add(this.clearVars);
            this.splitContainer1.Panel2.Controls.Add(this.clearButton);
            this.splitContainer1.Panel2.Controls.Add(this.executeButton);
            this.splitContainer1.Panel2.Controls.Add(this.invalidBox);
            this.splitContainer1.Panel2.Controls.Add(this.commandBox);
            this.splitContainer1.Panel2.Controls.Add(this.enterButton);
            this.splitContainer1.Panel2.Controls.Add(this.textBox1);
            this.splitContainer1.Panel2.Paint += new System.Windows.Forms.PaintEventHandler(this.splitContainer1_Panel2_Paint);
            this.splitContainer1.Panel2MinSize = 20;
            this.splitContainer1.Size = new System.Drawing.Size(850, 730);
            this.splitContainer1.SplitterDistance = 500;
            this.splitContainer1.TabIndex = 0;
            this.splitContainer1.Text = "splitContainer1";
            // 
            // turtle
            // 
            this.turtle.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.turtle.BackColor = System.Drawing.Color.Black;
            this.turtle.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.turtle.Cursor = System.Windows.Forms.Cursors.Default;
            this.turtle.ImageLocation = "C:\\Users\\Jake\\Source\\Repos\\ASE-Assignment\\ASE-Assignment\\content\\turtle.png";
            this.turtle.Location = new System.Drawing.Point(37, 101);
            this.turtle.Name = "turtle";
            this.turtle.Size = new System.Drawing.Size(3, 3);
            this.turtle.TabIndex = 0;
            this.turtle.TabStop = false;
            // 
            // clearScreen
            // 
            this.clearScreen.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.clearScreen.Location = new System.Drawing.Point(373, 174);
            this.clearScreen.Name = "clearScreen";
            this.clearScreen.Size = new System.Drawing.Size(113, 23);
            this.clearScreen.TabIndex = 8;
            this.clearScreen.Text = "Clear Screen";
            this.clearScreen.UseVisualStyleBackColor = true;
            this.clearScreen.Click += new System.EventHandler(this.clearScreen_Click);
            // 
            // clearMethod
            // 
            this.clearMethod.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.clearMethod.Location = new System.Drawing.Point(373, 145);
            this.clearMethod.Name = "clearMethod";
            this.clearMethod.Size = new System.Drawing.Size(113, 23);
            this.clearMethod.TabIndex = 7;
            this.clearMethod.Text = "Clear Methods";
            this.clearMethod.UseVisualStyleBackColor = true;
            this.clearMethod.Click += new System.EventHandler(this.clearMethod_Click);
            // 
            // clearVars
            // 
            this.clearVars.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.clearVars.Location = new System.Drawing.Point(373, 116);
            this.clearVars.Name = "clearVars";
            this.clearVars.Size = new System.Drawing.Size(113, 23);
            this.clearVars.TabIndex = 6;
            this.clearVars.Text = "Clear Variables";
            this.clearVars.UseVisualStyleBackColor = true;
            this.clearVars.Click += new System.EventHandler(this.clearVars_Click);
            // 
            // clearButton
            // 
            this.clearButton.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.clearButton.Location = new System.Drawing.Point(373, 87);
            this.clearButton.Name = "clearButton";
            this.clearButton.Size = new System.Drawing.Size(113, 23);
            this.clearButton.TabIndex = 5;
            this.clearButton.Text = "Clear Commands";
            this.clearButton.UseVisualStyleBackColor = true;
            this.clearButton.Click += new System.EventHandler(this.clearButton_Click);
            // 
            // executeButton
            // 
            this.executeButton.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.executeButton.Location = new System.Drawing.Point(373, 58);
            this.executeButton.Name = "executeButton";
            this.executeButton.Size = new System.Drawing.Size(113, 23);
            this.executeButton.TabIndex = 4;
            this.executeButton.Text = "Execute";
            this.executeButton.UseVisualStyleBackColor = true;
            this.executeButton.Click += new System.EventHandler(this.executeButton_Click);
            // 
            // invalidBox
            // 
            this.invalidBox.AutoSize = true;
            this.invalidBox.Location = new System.Drawing.Point(684, 4);
            this.invalidBox.Name = "invalidBox";
            this.invalidBox.Size = new System.Drawing.Size(113, 15);
            this.invalidBox.TabIndex = 3;
            this.invalidBox.Text = "Invalid Commands: ";
            this.invalidBox.TextAlign = System.Drawing.ContentAlignment.TopRight;
            this.invalidBox.UseMnemonic = false;
            // 
            // commandBox
            // 
            this.commandBox.AutoSize = true;
            this.commandBox.Location = new System.Drawing.Point(4, 4);
            this.commandBox.Name = "commandBox";
            this.commandBox.Size = new System.Drawing.Size(72, 15);
            this.commandBox.TabIndex = 2;
            this.commandBox.Text = "Commands:";
            // 
            // enterButton
            // 
            this.enterButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.enterButton.Location = new System.Drawing.Point(775, 202);
            this.enterButton.Name = "enterButton";
            this.enterButton.Size = new System.Drawing.Size(75, 23);
            this.enterButton.TabIndex = 1;
            this.enterButton.Text = "Enter";
            this.enterButton.UseVisualStyleBackColor = true;
            this.enterButton.Click += new System.EventHandler(this.enterButton_Click);
            // 
            // textBox1
            // 
            this.textBox1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.textBox1.Location = new System.Drawing.Point(0, 203);
            this.textBox1.Name = "textBox1";
            this.textBox1.PlaceholderText = "Enter Command";
            this.textBox1.Size = new System.Drawing.Size(850, 23);
            this.textBox1.TabIndex = 0;
            // 
            // saveFileDialog1
            // 
            this.saveFileDialog1.Filter = "Text files (*.txt)|*.txt";
            // 
            // openFileDialog1
            // 
            this.openFileDialog1.FileName = "openFileDialog1";
            // 
            // consoleBox
            // 
            this.consoleBox.Dock = System.Windows.Forms.DockStyle.Right;
            this.consoleBox.Location = new System.Drawing.Point(856, 24);
            this.consoleBox.Multiline = true;
            this.consoleBox.Name = "consoleBox";
            this.consoleBox.ReadOnly = true;
            this.consoleBox.Size = new System.Drawing.Size(361, 730);
            this.consoleBox.TabIndex = 2;
            this.consoleBox.TextChanged += new System.EventHandler(this.textBox2_TextChanged);
            // 
            // Window
            // 
            this.AcceptButton = this.enterButton;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1217, 754);
            this.Controls.Add(this.consoleBox);
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "Window";
            this.Text = "ASE-Assignment";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.turtle)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }



        #endregion

        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.Button enterButton;
        private System.Windows.Forms.PictureBox turtle;
        private SaveFileDialog saveFileDialog1;
        private OpenFileDialog openFileDialog1;
        private MenuStrip menuStrip1;
        private ToolStripMenuItem menuFile;
        private ToolStripMenuItem menuLoad;
        private ToolStripMenuItem menuSave;
        private ToolStripMenuItem menuQuit;
        private Label commandBox;
        private Label invalidBox;
        private Button clearButton;
        private Button executeButton;
        private TextBox consoleBox;
        private Button clearVars;
        private Button clearMethod;
        private Button clearScreen;
    }
}

